/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package first_page;

import ankh.morpork.AnkhMorpork;
import static first_page.first_page.active_turn;
import static first_page.first_page.image1;
import static first_page.first_page.playerObj;
import static first_page.second_page.p;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.URL;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.JRadioButton;

/**
 *
 * @author user
 */
public class gameBoard extends javax.swing.JFrame {

    
    
AnkhMorpork obj = new AnkhMorpork();
String cards ="";
static int one = 1;
public static Player p;
String[] s1;
static beginTurn bt = new beginTurn();
static selectedCard sc = new selectedCard();
static cardDetails cd;
BufferedImage img = null;
String selectedCard;
public static Integer[] no_for_symbols;// = new Integer[4];
    /**
     * Creates new form gameBoard
     */
    public gameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tm1 = new javax.swing.JLabel();
        demon3 = new javax.swing.JLabel();
        Rmin1 = new javax.swing.JLabel();
        Ymin1 = new javax.swing.JLabel();
        Gbuild1 = new javax.swing.JLabel();
        Rbuild1 = new javax.swing.JLabel();
        Bbuild1 = new javax.swing.JLabel();
        Ybuild1 = new javax.swing.JLabel();
        Gmin1 = new javax.swing.JLabel();
        Bmin1 = new javax.swing.JLabel();
        troll1 = new javax.swing.JLabel();
        demon4 = new javax.swing.JLabel();
        troll3 = new javax.swing.JLabel();
        troll2 = new javax.swing.JLabel();
        demon2 = new javax.swing.JLabel();
        demon1 = new javax.swing.JLabel();
        tm2 = new javax.swing.JLabel();
        tm3 = new javax.swing.JLabel();
        tm4 = new javax.swing.JLabel();
        tm5 = new javax.swing.JLabel();
        tm6 = new javax.swing.JLabel();
        tm7 = new javax.swing.JLabel();
        tm8 = new javax.swing.JLabel();
        tm9 = new javax.swing.JLabel();
        tm10 = new javax.swing.JLabel();
        tm11 = new javax.swing.JLabel();
        tm12 = new javax.swing.JLabel();
        Rmin2 = new javax.swing.JLabel();
        Rmin3 = new javax.swing.JLabel();
        Rmin4 = new javax.swing.JLabel();
        Rmin5 = new javax.swing.JLabel();
        Rmin6 = new javax.swing.JLabel();
        Rmin7 = new javax.swing.JLabel();
        Rmin8 = new javax.swing.JLabel();
        Rmin9 = new javax.swing.JLabel();
        Rmin10 = new javax.swing.JLabel();
        Rmin11 = new javax.swing.JLabel();
        Rmin12 = new javax.swing.JLabel();
        Rbuild2 = new javax.swing.JLabel();
        Rbuild3 = new javax.swing.JLabel();
        Rbuild4 = new javax.swing.JLabel();
        Rbuild5 = new javax.swing.JLabel();
        Rbuild6 = new javax.swing.JLabel();
        Ymin2 = new javax.swing.JLabel();
        Ymin3 = new javax.swing.JLabel();
        Ymin4 = new javax.swing.JLabel();
        Ymin5 = new javax.swing.JLabel();
        Ymin6 = new javax.swing.JLabel();
        Ymin7 = new javax.swing.JLabel();
        Ymin8 = new javax.swing.JLabel();
        Ymin9 = new javax.swing.JLabel();
        Ymin10 = new javax.swing.JLabel();
        Ymin11 = new javax.swing.JLabel();
        Ymin12 = new javax.swing.JLabel();
        Ybuild2 = new javax.swing.JLabel();
        Ybuild3 = new javax.swing.JLabel();
        Ybuild4 = new javax.swing.JLabel();
        Ybuild5 = new javax.swing.JLabel();
        Ybuild6 = new javax.swing.JLabel();
        Gmin2 = new javax.swing.JLabel();
        Gmin3 = new javax.swing.JLabel();
        Gmin4 = new javax.swing.JLabel();
        Gmin5 = new javax.swing.JLabel();
        Gmin6 = new javax.swing.JLabel();
        Gmin7 = new javax.swing.JLabel();
        Gmin8 = new javax.swing.JLabel();
        Gmin9 = new javax.swing.JLabel();
        Gmin10 = new javax.swing.JLabel();
        Gmin11 = new javax.swing.JLabel();
        Gmin12 = new javax.swing.JLabel();
        Gbuild2 = new javax.swing.JLabel();
        Gbuild3 = new javax.swing.JLabel();
        Gbuild4 = new javax.swing.JLabel();
        Gbuild5 = new javax.swing.JLabel();
        Gbuild6 = new javax.swing.JLabel();
        Bmin2 = new javax.swing.JLabel();
        Bmin3 = new javax.swing.JLabel();
        Bmin4 = new javax.swing.JLabel();
        Bmin5 = new javax.swing.JLabel();
        Bmin6 = new javax.swing.JLabel();
        Bmin7 = new javax.swing.JLabel();
        Bmin8 = new javax.swing.JLabel();
        Bmin9 = new javax.swing.JLabel();
        Bmin10 = new javax.swing.JLabel();
        Bmin11 = new javax.swing.JLabel();
        Bmin12 = new javax.swing.JLabel();
        Bbuild2 = new javax.swing.JLabel();
        Bbuild3 = new javax.swing.JLabel();
        Bbuild4 = new javax.swing.JLabel();
        Bbuild5 = new javax.swing.JLabel();
        Bbuild6 = new javax.swing.JLabel();
        Board = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        fundsLabel = new javax.swing.JLabel();
        playercardLabel = new javax.swing.JLabel();
        tmLabel = new javax.swing.JLabel();
        demonsLabel = new javax.swing.JLabel();
        trollsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        noplayerLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        gameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        playerAidButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        savegameButton = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        notify = new javax.swing.JLabel();
        beginTurnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1103, 800));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                place(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrange(evt);
            }
        });

        tm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm1.setOpaque(true);

        demon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N

        Rmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Ymin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Gbuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N

        Rbuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N

        Bbuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild1.setAutoscrolls(true);
        Bbuild1.setName(""); // NOI18N

        Ybuild1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N

        Gmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Bmin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        troll1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/troll.png"))); // NOI18N

        demon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N

        troll3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/troll.png"))); // NOI18N

        troll2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/troll.png"))); // NOI18N

        demon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N

        demon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/demon.png"))); // NOI18N

        tm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm2.setOpaque(true);

        tm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm3.setOpaque(true);

        tm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm4.setOpaque(true);

        tm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm5.setOpaque(true);

        tm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm6.setOpaque(true);

        tm7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm7.setOpaque(true);

        tm8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm8.setOpaque(true);

        tm9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm9.setOpaque(true);

        tm10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm10.setOpaque(true);

        tm11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm11.setOpaque(true);

        tm12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/TM.png"))); // NOI18N
        tm12.setOpaque(true);

        Rmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rmin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minR.png"))); // NOI18N

        Rbuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N

        Rbuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N

        Rbuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N

        Rbuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N

        Rbuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildR.png"))); // NOI18N

        Ymin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ymin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minY.png"))); // NOI18N

        Ybuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N

        Ybuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N

        Ybuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N

        Ybuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N

        Ybuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildY.png"))); // NOI18N

        Gmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gmin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minG.png"))); // NOI18N

        Gbuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N

        Gbuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N

        Gbuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N

        Gbuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N

        Gbuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildG.png"))); // NOI18N

        Bmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bmin12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/minB.png"))); // NOI18N

        Bbuild2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild2.setAutoscrolls(true);
        Bbuild2.setName(""); // NOI18N

        Bbuild3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild3.setAutoscrolls(true);
        Bbuild3.setName(""); // NOI18N

        Bbuild4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild4.setAutoscrolls(true);
        Bbuild4.setName(""); // NOI18N

        Bbuild5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild5.setAutoscrolls(true);
        Bbuild5.setName(""); // NOI18N

        Bbuild6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/buildB.png"))); // NOI18N
        Bbuild6.setAutoscrolls(true);
        Bbuild6.setName(""); // NOI18N

        Board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gboard/img/board.jpg"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("   Bank Status");
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLabel6.setText("Area Cards:");

        jLabel7.setText("Available Funds:");

        jLabel8.setText("Player cards Remaining:");

        jLabel9.setText("Trouble Markers:");

        jLabel10.setText("Demons:");

        jLabel11.setText("Trolls:");

        tmLabel.setText("9");

        demonsLabel.setText("4");

        trollsLabel.setText("3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fundsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(areaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trollsLabel)
                            .addComponent(demonsLabel)
                            .addComponent(tmLabel)
                            .addComponent(playercardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(areaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fundsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playercardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tmLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(demonsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(trollsLabel))
                .addGap(42, 42, 42))
        );

        jLabel2.setText("Total Players:");

        noplayerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noplayerLabel.setMaximumSize(new java.awt.Dimension(120, 120));

        jLabel4.setText("Current Player:");

        gameLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        gameLabel.setForeground(new java.awt.Color(0, 102, 255));
        gameLabel.setText("game statistic");
        gameLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(currentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(noplayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(noplayerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(colorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(currentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        playerAidButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        playerAidButton.setForeground(new java.awt.Color(0, 102, 255));
        playerAidButton.setText("Player Aid Card");
        playerAidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerAidButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 102, 255));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Give name for the file:");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        savegameButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        savegameButton.setForeground(new java.awt.Color(0, 102, 255));
        savegameButton.setText("Save Game");
        savegameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savegameButtonActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 102, 255));
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        notify.setText("Please give a name for the file");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(notify))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(savegameButton)
                        .addGap(14, 14, 14)
                        .addComponent(cancel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(nameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nameText))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(playerAidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(playerAidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savegameButton)
                    .addComponent(cancel))
                .addGap(18, 18, 18)
                .addComponent(notify)
                .addContainerGap())
        );

        beginTurnButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        beginTurnButton.setForeground(new java.awt.Color(0, 102, 255));
        beginTurnButton.setText("Begin Turn");
        beginTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginTurnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tm1)
                        .addGap(7, 7, 7)
                        .addComponent(tm2)
                        .addGap(7, 7, 7)
                        .addComponent(tm3)
                        .addGap(7, 7, 7)
                        .addComponent(tm4)
                        .addGap(7, 7, 7)
                        .addComponent(tm5)
                        .addGap(7, 7, 7)
                        .addComponent(tm6)
                        .addGap(7, 7, 7)
                        .addComponent(tm7)
                        .addGap(7, 7, 7)
                        .addComponent(tm8)
                        .addGap(7, 7, 7)
                        .addComponent(tm9)
                        .addGap(7, 7, 7)
                        .addComponent(tm10)
                        .addGap(7, 7, 7)
                        .addComponent(tm11)
                        .addGap(7, 7, 7)
                        .addComponent(tm12)
                        .addGap(47, 47, 47)
                        .addComponent(troll1)
                        .addGap(12, 12, 12)
                        .addComponent(troll2)
                        .addGap(12, 12, 12)
                        .addComponent(troll3)
                        .addGap(22, 22, 22)
                        .addComponent(demon1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(demon2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(demon3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(demon4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(538, 538, 538)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Board)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(beginTurnButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(Rmin1)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin2)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin3)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin4)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin6)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin5)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin7)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin8)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin9)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin10)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin11)
                                        .addGap(9, 9, 9)
                                        .addComponent(Rmin12)
                                        .addGap(19, 19, 19)
                                        .addComponent(Gmin1)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin2)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin3)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin4)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin5)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin6)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin7)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin8)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin9)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin10)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin11)
                                        .addGap(9, 9, 9)
                                        .addComponent(Gmin12)
                                        .addGap(19, 19, 19)
                                        .addComponent(Bmin1)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin2)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin3)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin4)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin5)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin6)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Bmin8)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin9)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin10)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin11)
                                        .addGap(9, 9, 9)
                                        .addComponent(Bmin12)
                                        .addGap(19, 19, 19)
                                        .addComponent(Ymin1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(Rbuild1)
                                        .addGap(13, 13, 13)
                                        .addComponent(Rbuild2)
                                        .addGap(13, 13, 13)
                                        .addComponent(Rbuild3)
                                        .addGap(13, 13, 13)
                                        .addComponent(Rbuild4)
                                        .addGap(13, 13, 13)
                                        .addComponent(Rbuild5)
                                        .addGap(13, 13, 13)
                                        .addComponent(Rbuild6)
                                        .addGap(143, 143, 143)
                                        .addComponent(Gbuild1)
                                        .addGap(13, 13, 13)
                                        .addComponent(Gbuild2)
                                        .addGap(13, 13, 13)
                                        .addComponent(Gbuild3)
                                        .addGap(13, 13, 13)
                                        .addComponent(Gbuild4)
                                        .addGap(13, 13, 13)
                                        .addComponent(Gbuild5)
                                        .addGap(13, 13, 13)
                                        .addComponent(Gbuild6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(140, 140, 140)
                                        .addComponent(Bbuild1)
                                        .addGap(13, 13, 13)
                                        .addComponent(Bbuild2)
                                        .addGap(13, 13, 13)
                                        .addComponent(Bbuild3)
                                        .addGap(13, 13, 13)
                                        .addComponent(Bbuild4)
                                        .addGap(13, 13, 13)
                                        .addComponent(Bbuild5)
                                        .addGap(13, 13, 13)
                                        .addComponent(Bbuild6)
                                        .addGap(143, 143, 143)
                                        .addComponent(Ybuild1)
                                        .addGap(13, 13, 13)
                                        .addComponent(Ybuild2)
                                        .addGap(13, 13, 13)
                                        .addComponent(Ybuild3)
                                        .addGap(13, 13, 13)
                                        .addComponent(Ybuild4)
                                        .addGap(13, 13, 13)
                                        .addComponent(Ybuild5)
                                        .addGap(13, 13, 13)
                                        .addComponent(Ybuild6)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ymin9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Ymin12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(beginTurnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(troll1)
                                    .addComponent(troll2)
                                    .addComponent(troll3)
                                    .addComponent(demon1)
                                    .addComponent(demon2)
                                    .addComponent(demon3)
                                    .addComponent(demon4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tm1)
                                            .addComponent(tm2)
                                            .addComponent(tm3)
                                            .addComponent(tm4)
                                            .addComponent(tm5)
                                            .addComponent(tm6)
                                            .addComponent(tm7)
                                            .addComponent(tm8)
                                            .addComponent(tm9)
                                            .addComponent(tm10)
                                            .addComponent(tm11)
                                            .addComponent(tm12))))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rmin2)
                                    .addComponent(Rmin3)
                                    .addComponent(Rmin4)
                                    .addComponent(Rmin6)
                                    .addComponent(Rmin5)
                                    .addComponent(Rmin7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rmin8)
                                    .addComponent(Rmin9)
                                    .addComponent(Rmin10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rmin11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rmin12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gmin1)
                                    .addComponent(Gmin2)
                                    .addComponent(Gmin3)
                                    .addComponent(Gmin4)
                                    .addComponent(Gmin5)
                                    .addComponent(Gmin6)
                                    .addComponent(Gmin7)
                                    .addComponent(Gmin8)
                                    .addComponent(Gmin9)
                                    .addComponent(Gmin10)
                                    .addComponent(Gmin11)
                                    .addComponent(Gmin12)
                                    .addComponent(Bmin1)
                                    .addComponent(Bmin2)
                                    .addComponent(Bmin3)
                                    .addComponent(Bmin4)
                                    .addComponent(Bmin5)
                                    .addComponent(Bmin6)
                                    .addComponent(Bmin7)
                                    .addComponent(Bmin8)
                                    .addComponent(Bmin9)
                                    .addComponent(Bmin10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bmin11)
                                    .addComponent(Bmin12)
                                    .addComponent(Ymin1)
                                    .addComponent(Ymin2)
                                    .addComponent(Ymin3)
                                    .addComponent(Ymin4)
                                    .addComponent(Ymin5)
                                    .addComponent(Ymin6)
                                    .addComponent(Ymin7)
                                    .addComponent(Ymin8)
                                    .addComponent(Ymin9)
                                    .addComponent(Ymin10)
                                    .addComponent(Ymin11))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rbuild1)
                                    .addComponent(Rbuild2)
                                    .addComponent(Rbuild3)
                                    .addComponent(Rbuild4)
                                    .addComponent(Rbuild5)
                                    .addComponent(Rbuild6)
                                    .addComponent(Gbuild1)
                                    .addComponent(Gbuild2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gbuild3)
                                    .addComponent(Gbuild4)
                                    .addComponent(Gbuild5)
                                    .addComponent(Gbuild6)
                                    .addComponent(Bbuild1)
                                    .addComponent(Bbuild2)
                                    .addComponent(Bbuild3)
                                    .addComponent(Bbuild4)
                                    .addComponent(Bbuild5)
                                    .addComponent(Bbuild6)
                                    .addComponent(Ybuild1)
                                    .addComponent(Ybuild2)
                                    .addComponent(Ybuild3)
                                    .addComponent(Ybuild4)
                                    .addComponent(Ybuild5)
                                    .addComponent(Ybuild6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Board, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Ymin12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setBounds(0, 0, 1322, 753);
    }// </editor-fold>//GEN-END:initComponents

    private void place(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_place
    
    }//GEN-LAST:event_place

    private void arrange(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrange
    //Demo display for TMs positions in each area
        tm1.setBounds(160, 265, 13, 13);       
        tm2.setBounds(260, 330, 13, 13); 
        tm3.setBounds(320, 125, 13, 13); 
        tm4.setBounds(480, 120, 13, 13);       
        tm5.setBounds(550, 290, 13, 13); 
        tm6.setBounds(680, 170, 13, 13);
        tm7.setBounds(670, 340, 13, 13);       
        tm8.setBounds(700, 530, 13, 13); 
        tm9.setBounds(510, 620, 13, 13);
        tm10.setBounds(460, 380, 13, 13);       
        tm11.setBounds(370, 540, 13, 13); 
        tm12.setBounds(210, 520, 13, 13);
   //Demo display for Buildings positions in each area
        Gbuild1.setBounds(180, 340, 7, 18);       
        Gbuild2.setBounds(260, 350, 7, 18);  
        Gbuild3.setBounds(210, 550, 7, 18);   
        Rbuild1.setBounds(330, 150, 7, 18);        
        Rbuild2.setBounds(480, 150, 7, 18);
        Rbuild3.setBounds(630, 260, 7, 18); 
        Bbuild1.setBounds(760, 190, 7, 18);      
        Bbuild2.setBounds(670, 380, 7, 18);
        Bbuild3.setBounds(690, 560, 7, 18);
        Ybuild1.setBounds(590, 650, 7, 18);      
        Ybuild2.setBounds(530, 410, 7, 18);
        Ybuild3.setBounds(370, 570, 7, 18);
    //Demo display for Demons positions in each area
        demon1.setBounds(580, 90, 8, 17);       
        demon2.setBounds(750, 120, 8, 17);  
        demon3.setBounds(870, 420, 8, 17);   
        demon4.setBounds(510, 430, 8, 17);      
    //Demo display for Trolls positions in each area
        troll1.setBounds(590, 410, 18, 12);       
        troll2.setBounds(860, 320, 18, 12);  
        troll3.setBounds(520, 670, 18, 12);   
    //Demo display for minions positions in area9
        Gmin4.setBounds(540, 610, 11, 11);
        Gmin5.setBounds(540, 620, 11, 11);
        Gmin6.setBounds(540, 630, 11, 11);
        Gmin7.setBounds(540, 640, 11, 11);
        Gmin8.setBounds(540, 650, 11, 11);
        Gmin9.setBounds(540, 660, 11, 11);
        Gmin10.setBounds(555, 610, 11, 11);
        Gmin11.setBounds(555, 620, 11, 11);
        Gmin12.setBounds(555, 630, 11, 11);
        Bmin4.setBounds(555, 640, 11, 11);
        Bmin5.setBounds(555, 650, 11, 11);
        Bmin6.setBounds(555, 660, 11, 11);
        
        for(int i=0;i<first_page.playerObj.length;i++){
            if(first_page.playerObj[i].Color == "red"){
        Rmin1.setBounds(200, 280, 11, 11);
        Rmin2.setBounds(570, 280, 11, 11);
        Rmin3.setBounds(710, 320, 11, 11);
            }
        if(first_page.playerObj[i].Color == "green"){
        Gmin1.setBounds(200, 290, 11, 11);
        Gmin2.setBounds(570, 290, 11, 11);
        Gmin3.setBounds(710, 330, 11, 11);
        }
        if(first_page.playerObj[i].Color == "blue"){
        Bmin1.setBounds(200, 300, 11, 11);
        Bmin2.setBounds(570, 300, 11, 11);
        Bmin3.setBounds(710, 340, 11, 11);
        }
        if(first_page.playerObj[i].Color == "yellow"){
        Ymin1.setBounds(200, 310, 11, 11);
        Ymin2.setBounds(570, 310, 11, 11);
        Ymin3.setBounds(710, 350, 11, 11);
        }
        }
    }//GEN-LAST:event_arrange

    private void playerAidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerAidButtonActionPerformed
        
        first_page.image1.setVisible(true);
        
        image1.events.setVisible(false);
        image1.imageLabel.setVisible(false);
        image1.personality.setVisible(false);
        image1.playerAid.setVisible(true);
        
    }//GEN-LAST:event_playerAidButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        cancel.setVisible(true);
        if(first_page.active_turn == -1)
            first_page.active_turn = 0;

        nameLabel.setVisible(true);
        nameText.setVisible(true);
     //   BendTurn.setVisible(false);
        savegameButton.setVisible(true);
        p = new Player();
        p.save_turn = first_page.active_turn;
        
        System.out.println("save turn variable: " + p.save_turn);        
        System.out.println("players detail:\n\t");
        
        for(int i =0;i<playerObj.length;i++){          
            System.out.println("player: " +(i+1) + "\n\t" + "Personality: " + playerObj[i].Personality + "\n\t" + "Color: " + playerObj[i].Color + "\n\t" + "Cash in hand:" +  playerObj[i].cashInHand + "\n\t" + "turn:" + playerObj[i].turn + "\n\t" + "buildings: "+ playerObj[i].buildInHand + "\n\t" + "minions: " + playerObj[i].minionInHand + "\n\t" + "cards: " +"\t" );
            for(int j=0;j<5;j++)
            System.out.println(first_page.playerObj[i].CardsInHand[j]);
        }
            

    }//GEN-LAST:event_saveButtonActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void savegameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savegameButtonActionPerformed
       
    if(nameText.getText().equals(""))
            notify.setText("Please Select a file");
        else
        {
            
        /*
        storing all the values for each players by calling ls.func()
        */

        FileOutputStream fileOut = null;
     try {
         fileOut = new FileOutputStream(nameText.getText() + ".ser");
     } catch (FileNotFoundException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
         ObjectOutputStream out = null;
     try {
         out = new ObjectOutputStream(fileOut);
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
     try {
         out.writeObject(playerObj);
         out.writeInt(playerObj.length);
         for(Player obj : playerObj)
             out.writeObject(obj);
         
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
     try {
         out.close();
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
     try {
         fileOut.close();
     } catch (IOException ex) {
         Logger.getLogger(second_page.class.getName()).log(Level.SEVERE, null, ex);
     }
         System.out.printf("Serialized data is saved in /tmp/employee.ser");
            
        }

    }//GEN-LAST:event_savegameButtonActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed

        savegameButton.setVisible(false);
        nameLabel.setVisible(false);
        nameText.setVisible(false);
        cancel.setVisible(false);
        notify.setVisible(false);
            
    }//GEN-LAST:event_cancelActionPerformed

    private void beginTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginTurnButtonActionPerformed

        beginTurnButton.setEnabled(false);
        bt.setLayout(new FlowLayout()); 
        bt.setVisible(true);
        cards= "";
        bt.playerLabel.setText("Player " + (active_turn+1));
        bt.colorLabel.setText(playerObj[0].Color);
        bt.colorLabel.setForeground(Color.getColor(playerObj[0].Color));
        if(playerObj[active_turn].isHuman)
            bt.hcLabel.setText("H"); 
        else
            bt.hcLabel.setText("C");
        
        
        bt.personalityLabel.setText(playerObj[0].Personality);
        bt.cashLabel.setText(String.valueOf(playerObj[0].cashInHand));
        bt.minionsLabel.setText(String.valueOf(playerObj[0].minionInHand));
        bt.buildingsLabel.setText(String.valueOf(playerObj[0].buildInHand));
        bt.areasLabel.setText("0");
        for(int j=0;j<5;j++)
            cards += playerObj[0].CardsInHand[j] + "  ";
        
        bt.cardsLabel.setText(cards);

        // display cards in hands
        
        for(int i=0;i<playerObj[0].CardsInHand.length;i++){
    
            URL iconURL = getClass().getResource("\\green cards\\" + playerObj[0].CardsInHand[i] + ".png" );
            ImageIcon icon = new ImageIcon(iconURL);
            
            bt.rb[i] = new JRadioButton();
            bt.rb[i].setName(playerObj[0].CardsInHand[i]);
            bt.jp.add(bt.rb[i]);
            bt.radioGroup.add(bt.rb[i]);
            bt.rb[0].isSelected();
        
            
            
            bt.lb[i] = new JLabel();
            bt.lb[i].setIcon(icon);
            bt.jp.add(bt.lb[i]);
            bt.add(bt.jp); 
                  
  
        }
        bt.rb[0].setSelected(true);
        bt.jb = new JButton("Play Card");
        bt.add(bt.jb,BorderLayout.CENTER);

        
        
        bt.jb.addActionListener(new ActionListener() {
 
            public void actionPerformed(ActionEvent e)
            {
                bt.setVisible(false);
                sc.setVisible(true);
                sc.playerLabel.setText("Player " + (active_turn+1));
                sc.colorLabel.setText(playerObj[0].Color);
                sc.colorLabel.setForeground(Color.getColor(playerObj[0].Color));
                if(playerObj[active_turn].isHuman)
                    sc.ishumanLabel.setText("H"); 
                else
                    sc.ishumanLabel.setText("C");
            
            
                // get the name of the selected card
                
            for (Enumeration<AbstractButton> buttons = bt.radioGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

                if (button.isSelected()) {
                    selectedCard = button.getName();
                }
            }
                System.out.println("selected card:" + selectedCard);
                
            //    cardDetails s = null;
           for (cardDetails s : cardDetails.values())
            {
                if (selectedCard.equals(s.toString()))
                {
                    for(int i=0;i<s.action.length;i++)
                    {
                      
                        System.out.printf("selected card name: %s and actions: %d",s.getName(),s.getAction(i));
                    //    no_for_symbols[i] = s.getAction(i) ;
                    }
                }
            }
           /*
             // display symbols for selected card
                for(int i=0;i<no_for_symbols.length;i++){

                URL iconURL = getClass().getResource("\\symbols\\" + no_for_symbols[i] + ".png" );
                ImageIcon icon = new ImageIcon(iconURL);

                bt.rb[i] = new JRadioButton();
                bt.rb[i].setName(playerObj[0].CardsInHand[i]);
                bt.jp.add(bt.rb[i]);
                bt.radioGroup.add(bt.rb[i]);
                bt.rb[0].isSelected();



                bt.lb[i] = new JLabel();
                bt.lb[i].setIcon(icon);
                bt.jp.add(bt.lb[i]);
                bt.add(bt.jp); 


                }*/
           /*     bt.rb[0].setSelected(true);
                bt.jb = new JButton("Play Card");
                bt.add(bt.jb,BorderLayout.CENTER);

*/
                
                
                
                
                
                
                
                
                
                
                
                // System.out.println("You clicked the button");
            }
        }); 
    }//GEN-LAST:event_beginTurnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  /*      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameBoard().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bbuild1;
    private javax.swing.JLabel Bbuild2;
    private javax.swing.JLabel Bbuild3;
    private javax.swing.JLabel Bbuild4;
    private javax.swing.JLabel Bbuild5;
    private javax.swing.JLabel Bbuild6;
    private javax.swing.JLabel Bmin1;
    private javax.swing.JLabel Bmin10;
    private javax.swing.JLabel Bmin11;
    private javax.swing.JLabel Bmin12;
    private javax.swing.JLabel Bmin2;
    private javax.swing.JLabel Bmin3;
    private javax.swing.JLabel Bmin4;
    private javax.swing.JLabel Bmin5;
    private javax.swing.JLabel Bmin6;
    private javax.swing.JLabel Bmin7;
    private javax.swing.JLabel Bmin8;
    private javax.swing.JLabel Bmin9;
    private javax.swing.JLabel Board;
    private javax.swing.JLabel Gbuild1;
    private javax.swing.JLabel Gbuild2;
    private javax.swing.JLabel Gbuild3;
    private javax.swing.JLabel Gbuild4;
    private javax.swing.JLabel Gbuild5;
    private javax.swing.JLabel Gbuild6;
    private javax.swing.JLabel Gmin1;
    private javax.swing.JLabel Gmin10;
    private javax.swing.JLabel Gmin11;
    private javax.swing.JLabel Gmin12;
    private javax.swing.JLabel Gmin2;
    private javax.swing.JLabel Gmin3;
    private javax.swing.JLabel Gmin4;
    private javax.swing.JLabel Gmin5;
    private javax.swing.JLabel Gmin6;
    private javax.swing.JLabel Gmin7;
    private javax.swing.JLabel Gmin8;
    private javax.swing.JLabel Gmin9;
    private javax.swing.JLabel Rbuild1;
    private javax.swing.JLabel Rbuild2;
    private javax.swing.JLabel Rbuild3;
    private javax.swing.JLabel Rbuild4;
    private javax.swing.JLabel Rbuild5;
    private javax.swing.JLabel Rbuild6;
    private javax.swing.JLabel Rmin1;
    private javax.swing.JLabel Rmin10;
    private javax.swing.JLabel Rmin11;
    private javax.swing.JLabel Rmin12;
    private javax.swing.JLabel Rmin2;
    private javax.swing.JLabel Rmin3;
    private javax.swing.JLabel Rmin4;
    private javax.swing.JLabel Rmin5;
    private javax.swing.JLabel Rmin6;
    private javax.swing.JLabel Rmin7;
    private javax.swing.JLabel Rmin8;
    private javax.swing.JLabel Rmin9;
    private javax.swing.JLabel Ybuild1;
    private javax.swing.JLabel Ybuild2;
    private javax.swing.JLabel Ybuild3;
    private javax.swing.JLabel Ybuild4;
    private javax.swing.JLabel Ybuild5;
    private javax.swing.JLabel Ybuild6;
    private javax.swing.JLabel Ymin1;
    private javax.swing.JLabel Ymin10;
    private javax.swing.JLabel Ymin11;
    private javax.swing.JLabel Ymin12;
    private javax.swing.JLabel Ymin2;
    private javax.swing.JLabel Ymin3;
    private javax.swing.JLabel Ymin4;
    private javax.swing.JLabel Ymin5;
    private javax.swing.JLabel Ymin6;
    private javax.swing.JLabel Ymin7;
    private javax.swing.JLabel Ymin8;
    private javax.swing.JLabel Ymin9;
    public javax.swing.JLabel areaLabel;
    public javax.swing.JButton beginTurnButton;
    public javax.swing.JButton cancel;
    public javax.swing.JLabel colorLabel;
    public javax.swing.JLabel currentLabel;
    private javax.swing.JLabel demon1;
    private javax.swing.JLabel demon2;
    private javax.swing.JLabel demon3;
    private javax.swing.JLabel demon4;
    public javax.swing.JLabel demonsLabel;
    public javax.swing.JLabel fundsLabel;
    public javax.swing.JLabel gameLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel nameLabel;
    public javax.swing.JTextField nameText;
    public javax.swing.JLabel noplayerLabel;
    public javax.swing.JLabel notify;
    private javax.swing.JButton playerAidButton;
    public javax.swing.JLabel playercardLabel;
    private javax.swing.JButton saveButton;
    public javax.swing.JButton savegameButton;
    private javax.swing.JLabel tm1;
    private javax.swing.JLabel tm10;
    private javax.swing.JLabel tm11;
    private javax.swing.JLabel tm12;
    private javax.swing.JLabel tm2;
    private javax.swing.JLabel tm3;
    private javax.swing.JLabel tm4;
    private javax.swing.JLabel tm5;
    private javax.swing.JLabel tm6;
    private javax.swing.JLabel tm7;
    private javax.swing.JLabel tm8;
    private javax.swing.JLabel tm9;
    public javax.swing.JLabel tmLabel;
    private javax.swing.JLabel troll1;
    private javax.swing.JLabel troll2;
    private javax.swing.JLabel troll3;
    public javax.swing.JLabel trollsLabel;
    // End of variables declaration//GEN-END:variables
}
